namespace: myapp
working_dir: .
strict: true
output:
  file_path: /Fluid-Attacks-Results.csv
  format: CSV
strict: false
debug: true
file_size_limit: false
language: EN
apk:
  include:
    - glob(**/*.apk)
sast:
  include:
    - .
    - glob(*)
  exclude:
    - glob(**/node_modules/**)
    - glob(**/test/**)
sca:
  include:
    - .
  exclude:
    - glob(**/test/**)
