# .github/workflows/dev.yml
name: Standalone CLI
on: [push, pull_request]
jobs:
   machineStandalone:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@cabc1b3a06beda7df98e839fa2d84db9a4bdfee7
         - uses: docker://docker.io/fluidattacks/cli:latest
         name: machineStandalone
         with:
            args: skims scan .
