# .github/workflows/dev.yml
name: Standalone CLI
on: [push, pull_request]
jobs:
  machineStandalone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure git
        run: git config --global --add safe.directory /github/workspace
      - name: Run Fluid Attacks CLI
        uses: docker://docker.io/fluidattacks/cli:latest
        with:
          args: skims scan /github/workspace/configFile.yaml --csv
      - name: List files in workspace
        run: ls -la /github/workspace
      - name: Upload scan results
        uses: actions/upload-artifact@v2
        with:
          name: Fluid-Attacks-Results
          path: /github/workspace/Fluid-Attacks-Results.csv
