# .github/workflows/dev.yml
name: Standalone CLI
on: [push, pull_request]
jobs:
   machineStandalone:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repository
           uses: actions/checkout@v2
           with:
             repository: srodriguev/WackoPicko
         - name: Configure git
           run: git config --global --add safe.directory /github/workspace
         - name: Run Fluid Attacks CLI
           uses: docker://docker.io/fluidattacks/cli:latest
           with:
             args: skims scan configFile.yaml --csv
         - name: List files in workspace
           run: ls -la /github/workspace
         - name: Upload scan results
           uses: actions/upload-artifact@v2
           with:
             name: Fluid-Attacks-Results
             path: ./Fluid-Attacks-Results.csv
